/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Clientes: () => import('#controllers/clientes_controller'),
  Compras: () => import('#controllers/compras_controller'),
  Gateways: () => import('#controllers/gateways_controller'),
  Login: () => import('#controllers/login_controller'),
  Produtos: () => import('#controllers/produtos_controller'),
  Transacoes: () => import('#controllers/transacoes_controller'),
}
